# -*- coding: utf-8 -*-
"""OP mp4totext

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YcB-TlM9JxtfNxnuZv_AVIZR94uw15F1
"""

import moviepy.editor as mp
import speech_recognition as sr
import requests
from bs4 import BeautifulSoup

class transcript():
  def __init__(self,video,audio,r,data,rec):
    self.video = video
    self.audio = audio
    self.r = r
    self.data = data
    self.rec = rec

  def text(self):

    self.video = mp.VideoFileClip(" ")  # Your Video Here
    self.audio = self.video.audio
    self.audio.write_audiofile("Transcript.wav")
    self.r = sr.Recognizer()
    with sr.AudioFile("Transcript.wav") as source:
      self.data = self.r.record(source)

    self.rec = self.r.recognize_google(self.data)
    return self.rec

class censor():
  def __init__(self,response,soup,text,words,flag,wordsp,recsp):
    self.response = response
    self.soup = soup
    self.text = text
    self.words = words
    self.flag = flag
    self.wordsp = wordsp
    self.recsp = recsp

  def letter(self):
    self.response=requests.get('https://en.wikipedia.org/wiki/Category:English_profanity')
    self.soup = BeautifulSoup(self.response.text)
    self.text = self.soup.get_text()
    self.words = self.text[1422:2230]
    self.flag = 0
    self.wordsp = self.words.split()
    self.recsp = self.rec.split()
    for i in self.wordsp:
      if i==self.recsp:
        "Video is Censored"
        break
